DROP DATABASE IF EXISTS adlister_db;
CREATE DATABASE adlister_db;
USE adlister_db;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(240) NOT NULL UNIQUE,
  email VARCHAR(240) NOT NULL UNIQUE,
  password VARCHAR (240) NOT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS ads;
CREATE TABLE ads (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  FOREIGN KEY (user_id) REFERENCES users (id),
  PRIMARY KEY (id)
);